server:
  port: 8086
spring:
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  profiles:
    active: test
